### PR TITLE
Added CSVs for up to 100 of the top songs (per genius.com) of Eminem & xxxtentacon

### PR DESCRIPTION
**Pull request by alik604**

### CODE REVIEW

**Comment by rojagtap** [comment]
Great Work! Although I have one concern. The repo is directly linked to the blog and there is a chance others might want to clone the repo as well. So it would be confusing to directly put a WIP code to display as we'll be changing the distribution of the dataset. 

Do you mind making changes in a separate file and then commit as a separate notebook? Or maybe commit your changes to a separate branch? Once you get satisfactory results on the test data or random data, we will then merge /replace the files. Thank you!
P.S. thanks for reminding me about the license I will do it asap.

**Review by rojagtap — APPROVED** [review]
This is fine, I'll add this

**Comment by alik604** [comment]
Thank you for the kind words. This is my first venture into ML for NLP.

I didn't mean the add the notebook. I need to get better at Git. 
So far I haven't got good results, despite throwing a better model & more data at the problem. I'll LMK when/if I do.

**Comment by alik604** [comment]
Created 2nd pull. Had issues adding a commit. Git is hard haha

**Pull request closed without merging**
